title: CS Teaching Resources
description: A website that contains resources I've found and created
collections:
  outside_resources_posts:
    output: true
  course_specifics:
    output: true

# Build settings
theme: minima
plugins:
  - jekyll-feed

